"""
PyEngine CLI - Command line interface for creating and managing projects.

Usage:
    pyengine startproject <name>    Create a new project
    pyengine build                  Build executable
    pyengine run                    Run the project
    pyengine editor                 Launch the editor
    pyengine --version              Show version
    pyengine --help                 Show help

Example:
    pyengine startproject mygame
    cd mygame
    pyengine run
    pyengine build --onefile
"""

import os
import sys

# Add parent directory to path if running from source (ensures imports work correctly)
# This allows 'from engine.types import Color' to work
_cli_file = os.path.abspath(__file__)
_engine_pkg_dir = os.path.dirname(_cli_file)  # engine/
_project_root = os.path.dirname(_engine_pkg_dir)  # project root
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

import argparse
import subprocess
import json
from pathlib import Path
from typing import Optional, List, Dict, Any


# ============================================================================
# PROJECT TEMPLATES
# ============================================================================

# Template for main.py
MAIN_PY_TEMPLATE = '''"""
{project_name} - PyEngine Game
Generated by PyEngine CLI
"""
import sys
from pathlib import Path

# Add engine to path (if needed)
# sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from engine.d3 import Window3D, Scene3D, GameObject, Time
from engine.d3 import create_cube, create_sphere, create_plane
from engine.input import Keys
from engine.types import Color

# Import settings
from settings import GAME_TITLE, WINDOW_WIDTH, WINDOW_HEIGHT, FPS, INITIAL_SCENE


def _resolve_initial_scene(value):
    if isinstance(value, str) and value.strip().lower().endswith(".scene"):
        return Scene3D.load(value)

    if isinstance(value, str) and ":" in value:
        mod_name, cls_name = value.split(":", 1)
        module = __import__(mod_name, fromlist=[cls_name])
        cls = getattr(module, cls_name)
        return cls()

    if isinstance(value, type) and issubclass(value, Scene3D):
        return value()

    if isinstance(value, Scene3D):
        return value

    raise ValueError(
        "INITIAL_SCENE must be a .scene path string, a 'module:ClassName' string, "
        "a Scene3D subclass, or a Scene3D instance"
    )


class MainScene(Scene3D):
    """Main game scene."""
    
    def setup(self):
        """Called once at startup."""
        super().setup()
        
        # Create a simple cube
        self.cube = create_cube(
            position=(0, 0, 0),
            size=1.0,
            color=Color.ORANGE
        )
        self.add_object(self.cube)
        
        # Set up camera
        self.camera.position = (0, 5, 10)
        self.camera.look_at((0, 0, 0))
        
        # Set up light
        self.light.direction = (0.5, -1, -0.5)
        self.light.ambient = 0.3
        
        # Rotation speed
        self.rotation_speed = 30  # degrees per second
    
    def on_update(self):
        """Called every frame."""
        delta_time = Time.delta_time
        
        # Rotate the cube
        self.cube.transform.rotation_y += self.rotation_speed * delta_time
        
        # Update window title with FPS
        self.window.set_caption(f"{{GAME_TITLE}} - {{self.window.fps:.0f}} FPS")
    
    def on_key_press(self, key, modifiers):
        """Called when a key is pressed."""
        if key == Keys.ESCAPE:
            self.window.close()
        elif key == Keys.SPACE:
            # Toggle rotation
            self.rotation_speed = -self.rotation_speed


def main():
    """Main entry point."""
    print(f"Starting {{GAME_TITLE}}...")
    print("Controls:")
    print("  ESC   - Exit")
    print("  SPACE - Toggle rotation")
    print()
    
    # Create and run the game
    window = Window3D(WINDOW_WIDTH, WINDOW_HEIGHT, GAME_TITLE)
    scene = _resolve_initial_scene(INITIAL_SCENE)
    window.show_scene(scene)
    window.run(fps=FPS)


if __name__ == "__main__":
    main()
'''


# Template for settings.py
SETTINGS_PY_TEMPLATE = '''"""
{project_name} Settings

Configure your game settings here.
"""

# Game Window Settings
GAME_TITLE = "{project_name}"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60

# Rendering Settings
ENABLE_VSYNC = True
ENABLE_CULLING = True
ENABLE_INSTANCING = True

# Physics Settings
ENABLE_PHYSICS = True
GRAVITY = (0, -9.81, 0)

# Debug Settings
SHOW_FPS = True
SHOW_DEBUG_INFO = False
DEBUG_MODE = False

# Scene Settings
# Can be:
# - .scene path: "scenes/main.scene"
# - import string: "main:MainScene" or "scenes.menu:MenuScene"
# - Scene3D subclass / instance
INITIAL_SCENE = "main:MainScene"
'''


# Template for requirements.txt
REQUIREMENTS_TXT_TEMPLATE = """# Engine3D Game Dependencies
# Install with: pip install -r requirements.txt

# Core Engine3D Dependencies
pygame>=2.6.0
numpy>=1.20.0
pyglet>=2.1.0
pillow>=11.0.0
trimesh>=4.0.0
scipy>=1.10.0

# Optional: GPU Acceleration (recommended)
# moderngl>=5.6.0
# moderngl-window>=2.4.0

# Optional: Editor
# PySide6>=6.6.0

# Build tools (install when building)
# pyinstaller>=6.0.0
# nuitka>=2.0.0
"""


# Template for pyproject.toml (project-level)
PYPROJECT_TEMPLATE = """[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "A game built with Engine3D"
requires-python = ">=3.8"

dependencies = [
    "pygame>=2.6.0",
    "numpy>=1.20.0",
    "pyglet>=2.1.0",
    "pillow>=11.0.0",
    "trimesh>=4.0.0",
    "scipy>=1.10.0",
]

[tool.pyengine.build]
entry_point = "main.py"
output_name = "{project_name}"
icon = ""
include_assets = ["assets/", "scenes/", "scripts/", "settings.py"]
exclude_modules = ["pytest", "PySide6"]

[tool.pyengine.build.backends.pyinstaller]
onefile = false
console = false
windowed = true

[tool.pyengine.build.backends.nuitka]
onefile = false
standalone = true
enable_plugin = "pygame"
"""


# Template for README.md
README_MD_TEMPLATE = """# {project_name}

A 3D game built with Engine3D.

## Getting Started

### Installation

1. Create a virtual environment (recommended):
   ```bash
   python -m venv venv
   source venv/bin/activate  # On Windows: venv\\Scripts\\activate
   ```

2. Install dependencies:
   ```bash
   pip install -r requirements.txt
   ```

### Running the Game

```bash
# Using Engine3D CLI
pyengine run

# Or directly
python main.py
```

### Building Executable

```bash
# Build with default settings (PyInstaller)
pyengine build

# Build single executable file
pyengine build --onefile

# Build with Nuitka (better performance)
pyengine build --backend nuitka

# Build debug version with console
pyengine build --debug
```

### Project Structure

```
{project_name}/
├── main.py              # Game entry point
├── settings.py          # Game configuration
├── requirements.txt     # Dependencies
├── build.py             # Build script
├── assets/              # 3D models, textures, sounds
├── scenes/              # Scene definitions
└── scripts/             # Game scripts/components
```

### Controls

- **ESC** - Exit
- **SPACE** - Toggle rotation

## Development

### Adding 3D Models

Place your .obj files in the `assets/` folder and load them:

```python
self.player = self.load_object("assets/player.obj")
```

### Creating Scenes

Create new scenes in the `scenes/` folder:

```python
from engine.d3 import Scene3D

class MenuScene(Scene3D):
    def setup(self):
        # Setup menu UI and objects
        pass
```

## License

Add your license here.
"""


# Template for scripts/__init__.py
SCRIPTS_INIT_TEMPLATE = '''"""
Scripts Package

Add your custom scripts and components here.
"""
# from .player_controller import PlayerController
# from .enemy_ai import EnemyAI
'''


# Template for build.py
BUILD_PY_TEMPLATE = '''#!/usr/bin/env python3
"""
Build script for {project_name}.

This script can be used to build the game executable.
It supports multiple backends: PyInstaller and Nuitka.

Usage:
    python build.py                    # Build with default settings
    python build.py --backend nuitka   # Build with Nuitka
    python build.py --onefile          # Build single executable
    python build.py --clean            # Clean build files
"""
import sys
import argparse
from pathlib import Path

# Add engine to path if needed (when engine is in parent directory)
try:
    from engine.build import BuildSystem
except ImportError:
    # Try common locations
    engine_paths = [
        Path(__file__).parent.parent / "engine",  # sibling to project
        Path(__file__).parent.parent.parent / "engine",  # src/engine
        Path(__file__).parent.parent,  # project is inside engine
    ]
    for path in engine_paths:
        if path.exists() and (path / "engine" / "build.py").exists():
            sys.path.insert(0, str(path.parent if path.name == "engine" else path))
            break
    from engine.build import BuildSystem


def main():
    parser = argparse.ArgumentParser(
        description="Build {project_name} executable"
    )
    parser.add_argument(
        "--backend",
        choices=["pyinstaller", "nuitka"],
        default="pyinstaller",
        help="Build backend to use (default: pyinstaller)"
    )
    parser.add_argument(
        "--onefile",
        action="store_true",
        help="Build as single executable file"
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Build debug version with console"
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Clean build files"
    )
    
    args = parser.parse_args()
    
    if args.clean:
        BuildSystem.clean(Path(__file__).parent)
        return
    
    builder = BuildSystem(
        project_path=Path(__file__).parent,
        backend=args.backend
    )
    
    success = builder.build(
        onefile=args.onefile,
        debug=args.debug
    )
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
'''


# Template for .gitignore
GITIGNORE_TEMPLATE = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Build outputs
/dist/
/build/
*.spec
*.exe
*.app
*.dmg

# Engine3D specific
*.log
.cache/
"""


# ============================================================================
# PROJECT CREATION
# ============================================================================


def create_project(project_name: str, target_dir: Optional[Path] = None) -> Path:
    """
    Create a new Engine3D project with the given name.

    Args:
        project_name: Name of the project
        target_dir: Directory where project will be created (default: current directory)

    Returns:
        Path to the created project directory
    """
    # Determine target directory
    if target_dir is None:
        target_dir = Path.cwd()
    else:
        target_dir = Path(target_dir)

    # Create project directory
    project_path = target_dir / project_name

    if project_path.exists():
        print(f"Error: Directory '{project_path}' already exists.")
        sys.exit(1)

    # Create directory structure
    print(f"Creating project '{project_name}'...")

    project_path.mkdir(parents=True)
    (project_path / "assets").mkdir()
    (project_path / "scenes").mkdir()
    (project_path / "scripts").mkdir()

    # Create files
    files_to_create = [
        ("main.py", MAIN_PY_TEMPLATE),
        ("settings.py", SETTINGS_PY_TEMPLATE),
        ("requirements.txt", REQUIREMENTS_TXT_TEMPLATE),
        ("pyproject.toml", PYPROJECT_TEMPLATE),
        ("build.py", BUILD_PY_TEMPLATE),
        ("README.md", README_MD_TEMPLATE),
        (".gitignore", GITIGNORE_TEMPLATE),
        ("scripts/__init__.py", SCRIPTS_INIT_TEMPLATE),
        ("assets/.gitkeep", ""),
    ]

    for filename, template in files_to_create:
        filepath = project_path / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)
        content = template.format(project_name=project_name)
        filepath.write_text(content, encoding="utf-8")
        print(f"  Created {filename}")

    # Make build.py executable on Unix
    if os.name != "nt":
        build_py = project_path / "build.py"
        build_py.chmod(build_py.stat().st_mode | 0o111)

    print(f"\n✓ Project '{project_name}' created successfully!")
    print(f"  Location: {project_path.absolute()}")
    print(f"\nNext steps:")
    print(f"  cd {project_name}")
    print(f"  pip install -r requirements.txt")
    print(f"  pyengine run        # Run the game")
    print(f"  pyengine build      # Build executable")

    return project_path


# ============================================================================
# BUILD SYSTEM (for use in cli.py)
# ============================================================================


class BuildSystem:
    """Build system for Engine3D projects."""

    def __init__(self, project_path: Path, backend: str = "pyinstaller"):
        self.project_path = Path(project_path).resolve()
        self.backend = backend
        self.config = self._load_config()

    def _load_config(self) -> Dict[str, Any]:
        """Load build configuration from pyproject.toml."""
        config_file = self.project_path / "pyproject.toml"
        if not config_file.exists():
            # Use defaults
            return {
                "entry_point": "main.py",
                "output_name": self.project_path.name,
                "icon": "",
                "include_assets": ["assets/", "scenes/", "scripts/"],
                "exclude_modules": ["pytest", "PySide6"],
            }

        # Parse pyproject.toml manually (no external dependency)
        import re

        content = config_file.read_text()

        config = {}
        # Extract tool.engine.build section
        match = re.search(r"\[tool\.pyengine\.build\](.*?)(?=\[|$)", content, re.DOTALL)
        if match:
            section = match.group(1)
            # Parse key = value pairs
            for line in section.strip().split("\n"):
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    key, value = line.split("=", 1)
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    config[key] = value

        return config

    def build(self, onefile: bool = False, debug: bool = False) -> bool:
        """Build the project executable."""
        print(
            f"Building '{self.config.get('output_name', 'game')}' with {self.backend}..."
        )

        if self.backend == "pyinstaller":
            return self._build_pyinstaller(onefile, debug)
        elif self.backend == "nuitka":
            return self._build_nuitka(onefile, debug)
        else:
            print(f"Error: Unknown backend '{self.backend}'")
            return False

    def _build_pyinstaller(self, onefile: bool, debug: bool) -> bool:
        """Build using PyInstaller."""
        try:
            import PyInstaller.__main__
        except ImportError:
            print("PyInstaller not found. Installing...")
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "pyinstaller"], check=True
            )
            import PyInstaller.__main__

        entry_point = self.config.get("entry_point", "main.py")
        output_name = self.config.get("output_name", "game")
        icon = self.config.get("icon", "")

        args = [
            entry_point,
            "--name",
            output_name,
            "--distpath",
            "dist",
            "--workpath",
            "build",
            "--specpath",
            ".",
        ]

        if onefile:
            args.append("--onefile")
        else:
            args.append("--onedir")

        if not debug:
            args.append("--windowed")
        else:
            args.append("--console")

        if icon:
            args.extend(["--icon", icon])

        # Add assets
        for asset in self.config.get("include_assets", []):
            asset_path = self.project_path / asset
            if asset_path.exists():
                args.extend(["--add-data", f"{asset}{os.pathsep}{asset}"])

        # Exclude modules
        for module in self.config.get("exclude_modules", []):
            args.extend(["--exclude-module", module])

        print(f"Running: pyinstaller {' '.join(args)}")

        try:
            PyInstaller.__main__.run(args)
            print(f"\n✓ Build successful!")
            print(f"  Output: {self.project_path / 'dist' / output_name}")
            return True
        except Exception as e:
            print(f"\n✗ Build failed: {e}")
            return False

    def _build_nuitka(self, onefile: bool, debug: bool) -> bool:
        """Build using Nuitka."""
        # Check if nuitka is installed
        try:
            subprocess.run(
                [sys.executable, "-m", "nuitka", "--version"],
                capture_output=True,
                check=True,
            )
        except (subprocess.CalledProcessError, FileNotFoundError):
            print("Nuitka not found. Installing...")
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "nuitka"], check=True
            )

        entry_point = self.config.get("entry_point", "main.py")
        output_name = self.config.get("output_name", "game")

        args = [
            sys.executable,
            "-m",
            "nuitka",
            entry_point,
            "--output-dir=dist",
            "--output-filename=" + output_name,
            "--enable-plugin=pygame",
            "--include-package=engine",
        ]

        if onefile:
            args.append("--onefile")
        else:
            args.append("--standalone")

        if not debug:
            args.append("--windows-disable-console")

        # Add assets
        for asset in self.config.get("include_assets", []):
            asset_path = self.project_path / asset
            if asset_path.exists():
                args.extend(["--include-data-dir", f"{asset}={asset}"])

        print(f"Running: {' '.join(args)}")

        try:
            subprocess.run(args, cwd=self.project_path, check=True)
            print(f"\n✓ Build successful!")
            print(f"  Output: {self.project_path / 'dist' / output_name}")
            return True
        except subprocess.CalledProcessError as e:
            print(f"\n✗ Build failed: {e}")
            return False

    @staticmethod
    def clean(project_path: Path) -> None:
        """Clean build files."""
        print("Cleaning build files...")

        dirs_to_remove = ["build", "dist", "__pycache__"]
        files_to_remove = ["*.spec", "*.pyc", "*.pyo"]

        for dir_name in dirs_to_remove:
            path = project_path / dir_name
            if path.exists():
                import shutil

                shutil.rmtree(path)
                print(f"  Removed {dir_name}/")

        import glob

        for pattern in files_to_remove:
            for file in glob.glob(str(project_path / pattern)):
                Path(file).unlink()
                print(f"  Removed {Path(file).name}")

        print("✓ Clean complete")


def cmd_build(args) -> None:
    """Handle build command."""
    project_path = Path(args.project_path or ".").resolve()

    if not (project_path / "main.py").exists():
        print(f"Error: No main.py found in {project_path}")
        print("Make sure you're in a valid Engine3D project directory.")
        sys.exit(1)

    if args.clean:
        BuildSystem.clean(project_path)
        return

    builder = BuildSystem(project_path, backend=args.backend)
    success = builder.build(onefile=args.onefile, debug=args.debug)

    sys.exit(0 if success else 1)


# ============================================================================
# RUN COMMAND
# ============================================================================


def cmd_run(args) -> None:
    """Handle run command."""
    project_path = Path(args.project_path or ".").resolve()
    main_file = project_path / "main.py"

    if not main_file.exists():
        print(f"Error: No main.py found in {project_path}")
        print("Make sure you're in a valid Engine3D project directory.")
        sys.exit(1)

    print(f"Running project: {project_path.name}")

    try:
        # Run the main.py file
        result = subprocess.run(
            [sys.executable, str(main_file)] + args.args, cwd=project_path
        )
        sys.exit(result.returncode)
    except KeyboardInterrupt:
        print("\nGame stopped.")
        sys.exit(0)


# ============================================================================
# EDITOR COMMAND
# ============================================================================


def cmd_editor(args) -> None:
    """Handle editor command."""
    project_path = Path(args.project_path or ".").resolve()

    try:
        from .editor import run_editor

        run_editor(str(project_path))
    except ImportError as e:
        print(f"Error: Could not launch editor. {e}")
        print("Make sure PySide6 is installed: pip install PySide6")
        sys.exit(1)


# ============================================================================
# MAIN CLI
# ============================================================================


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="pyengine",
        description="Engine3D CLI - Create and manage 3D game projects",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  pyengine startproject mygame       Create a new project called 'mygame'
  pyengine run                       Run the current project
  pyengine build                     Build executable
  pyengine build --onefile           Build single executable file
  pyengine build --backend nuitka    Build with Nuitka
  pyengine editor                    Launch the editor
  pyengine --version                 Show version information
        """,
    )

    parser.add_argument("--version", action="version", version="%(prog)s 0.1.0")

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # startproject command
    startproject_parser = subparsers.add_parser(
        "startproject",
        help="Create a new Engine3D project",
        description="Create a new Engine3D project with the given name.",
    )
    startproject_parser.add_argument("name", help="Name of the project to create")
    startproject_parser.add_argument(
        "-d",
        "--directory",
        help="Directory where project will be created (default: current directory)",
        default=None,
    )

    # build command
    build_parser = subparsers.add_parser(
        "build",
        help="Build the project executable",
        description="Build the game as a standalone executable.",
    )
    build_parser.add_argument(
        "--backend",
        choices=["pyinstaller", "nuitka"],
        default="pyinstaller",
        help="Build backend to use (default: pyinstaller)",
    )
    build_parser.add_argument(
        "--onefile", action="store_true", help="Build as single executable file"
    )
    build_parser.add_argument(
        "--debug", action="store_true", help="Build debug version with console window"
    )
    build_parser.add_argument("--clean", action="store_true", help="Clean build files")
    build_parser.add_argument(
        "--project-path",
        help="Path to project directory (default: current directory)",
        default=None,
    )

    # run command
    run_parser = subparsers.add_parser(
        "run",
        help="Run the project",
        description="Run the game from the project directory.",
    )
    run_parser.add_argument(
        "--project-path",
        help="Path to project directory (default: current directory)",
        default=None,
    )
    run_parser.add_argument(
        "args",
        nargs=argparse.REMAINDER,
        help="Additional arguments to pass to the game",
        default=[],
    )

    # editor command
    editor_parser = subparsers.add_parser(
        "editor",
        help="Launch the Engine3D editor",
        description="Launch the visual editor for the project.",
    )
    editor_parser.add_argument(
        "--project-path",
        help="Path to project directory (default: current directory)",
        default=None,
    )

    # Parse arguments
    args = parser.parse_args()

    if args.command == "startproject":
        create_project(args.name, args.directory)
    elif args.command == "build":
        cmd_build(args)
    elif args.command == "run":
        cmd_run(args)
    elif args.command == "editor":
        cmd_editor(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
