from engine3d.physics3d.geometry import closest_point_on_triangle
from engine3d.physics3d.collision_manifold import (
    CollisionManifold,
    get_collision_manifold,
    sphere_vs_sphere_manifold,
    obb_vs_obb_manifold,
    sphere_vs_obb_manifold,
    cylinder_vs_sphere_manifold,
    cylinder_vs_cylinder_manifold,
    cylinder_vs_obb_manifold,
    sphere_vs_mesh_manifold,
    cylinder_vs_mesh_manifold,
)
from engine3d.physics3d.collision_bool import (
    objects_collide,
    collide_point_with_radius,
    aabb_overlap,
    sphere_vs_sphere_bool,
    obb_vs_obb_bool,
    sphere_vs_obb_bool,
    cylinder_vs_sphere_bool,
    cylinder_vs_cylinder_bool,
    cylinder_vs_obb_bool,
    sphere_vs_mesh_bool,
    cylinder_vs_mesh_bool,
)

# Re-export everything for backward compatibility
__all__ = [
    "CollisionManifold",
    "get_collision_manifold",
    "objects_collide",
    "collide_point_with_radius",
    "closest_point_on_triangle",
    "aabb_overlap",
    "sphere_vs_sphere_manifold",
    "obb_vs_obb_manifold",
    "sphere_vs_obb_manifold",
    "cylinder_vs_sphere_manifold",
    "cylinder_vs_cylinder_manifold",
    "cylinder_vs_obb_manifold",
    "sphere_vs_mesh_manifold",
    "cylinder_vs_mesh_manifold",
    "sphere_vs_sphere_bool",
    "obb_vs_obb_bool",
    "sphere_vs_obb_bool",
    "cylinder_vs_sphere_bool",
    "cylinder_vs_cylinder_bool",
    "cylinder_vs_obb_bool",
    "sphere_vs_mesh_bool",
    "cylinder_vs_mesh_bool",
]
